// @ts-check
// The editor's two field sets: `heroFields` (a page's hero, in frontmatter) and `templates`
// (every component an editor can insert into a page body).
//
// A block with prose inside it (a Split, a Callout) is a template with a `body` field of
// type `rich-text`. A self-closing block is a template without one.
//
// `required` on a template field is real: a page's body is a `blocks` list, so every
// template below becomes a GraphQL type and `required` makes its field non-null. Two
// members of that union may not return `String!` and `String` under the same field name,
// so a field name shared across templates has to agree — use `needed()` instead where it
// can't (see its note). `scripts/check-site.mjs` stays the backstop for alt text either
// way: it catches an image that was already saved, which is the case validation can't reach.
//
// Kept in .mjs so Node scripts and the CMS config can import it without a build step
// (the same reason as short-link-rules.mjs and video-rules.mjs).

import { checkVideoUrl } from './video-rules.mjs'
import { checkLinkUrl, checkOptionalLink } from './link-rules.mjs'
import { checkPhotoAlt, siblingValue } from './block-rules.mjs'
import photoCatalog from '../src/content/photos/photos.json' with { type: 'json' }

/** @typedef {Record<string, unknown>} FieldOpts */

/**
 * A validator's arguments as Tina passes them: the value, the whole document, final-form's
 * field state, and the field itself, whose `name` is its full path through the form.
 * @typedef {(value: unknown, allValues: unknown, meta?: unknown, field?: { name?: string }) => string | undefined} Validate
 */

/** Filenames the photo catalog describes, as of when this config was built. */
const CATALOGUED = new Set(photoCatalog.photos.map((p) => p.id.split('/').pop() ?? ''))

/*
 * How the help text is written, so every form reads alike. The audience is a volunteer
 * who has never seen the schema:
 *
 *   - One sentence, task-first: what to put here, not how the site uses it. Anything
 *     longer belongs in the editor's guide, linked with `guide()`.
 *   - A field that can be left blank says "(optional)" in its label, and nowhere else.
 *     Required fields say nothing; their validation speaks when it matters.
 *   - Say what a blank does only when it does something ("Leave blank for …").
 *   - Fields run Small label → Heading → Intro → Photo → Text → list → Button → how it
 *     looks (background, columns, photo side), so a block's form always reads top-down
 *     the way the block does.
 *   - The same idea gets the same words in every block: `button()` and `linkFields()`
 *     below, never a hand-written label for either.
 */

/**
 * A link from a field's help text to a page of the editor's guide (docs/manual/, served at
 * /webmaster/). Tina renders a description as HTML, so the link is live in the form; it is
 * root-relative because the admin is served from the same site as the guide, and opens in
 * a new tab so an editor doesn't lose an unsaved form by following it. Tina styles a
 * description's links exactly like its text, hence the inline underline.
 * @type {(page: string, text: string) => string}
 */
export const guide = (page, text) =>
  `<a href="/webmaster/${page}/" target="_blank" rel="noopener" style="text-decoration: underline">${text}</a>`

/**
 * A block's thumbnail in the CMS palette, shown above its name when the palette is open
 * (`ui.visualSelector` on the body field in tina/config.ts).
 *
 * Each one is a crop of the block as it really renders on the site, regenerated by
 * scripts/generate-block-previews.mjs — so the picker shows the thing itself rather than
 * a drawing of it, and a block that changes shape is one script run from being accurate
 * again. Served from public/, which prune-dist.mjs leaves alone.
 * @type {(name: string) => string}
 */
const preview = (name) => `/block-previews/${name}.webp`

/**
 * Editor-side "fill this in", for a field whose name is shared with another block.
 *
 * `required: true` can't be used on those. A page's body is a `blocks` list, so every
 * template is a real GraphQL type in one union, and two members of that union may not
 * return `String!` and `String` under the same field name — GraphQL's field-merging
 * rules reject the generated query outright, and codegen fails the build. `heading` is
 * optional in a Text block by design and `image` is optional in a Letter, so the
 * whole union has to spell both nullable.
 *
 * No guard is lost: `required` on a template field was always form-side only. This says
 * the same thing in the one place that still can.
 * @type {(message: string) => Record<string, unknown>}
 */
const needed = (message) => ({
  ui: {
    /** @type {(value: unknown) => string | undefined} */
    validate: (value) => (typeof value === 'string' && value.trim() ? undefined : message),
  },
})

/**
 * A wrapper block's prose.
 *
 * The toolbar is inline formatting only. `image` is absent because these blocks carry
 * their own image fields, and `embed` because TinaChildren.astro renders a block's body
 * with the inline overrides alone — a block nested inside a block would save fine and
 * then render as nothing. Everything else Tina offers (raw, table, code, mermaid,
 * highlight, strikethrough) has no styling anywhere in src/styles, so it's out too.
 *
 * Heading levels default to h3 and below: a wrapper block renders its own `heading`
 * field as an h2 (Band.astro), and the page hero owns the only h1. The exception is a
 * block whose heading is optional — pass ['h2', 'h3', 'h4'] there so prose in a
 * headingless one doesn't jump straight from h1 to h3.
 */
/** @type {(headingLevels?: string[]) => Record<string, unknown>} */
const prose = (headingLevels = ['h3', 'h4']) => ({
  name: 'body',
  label: 'Text',
  type: 'rich-text',
  overrides: {
    toolbar: ['heading', 'link', 'quote', 'ul', 'ol', 'bold', 'italic'],
    headingLevels,
  },
})

/** @type {(name: string, label: string, opts?: FieldOpts) => Record<string, unknown>} */
const text = (name, label, opts = {}) => ({ name, label, type: 'string', ...opts })

/** @type {(name: string, label: string, opts?: FieldOpts) => Record<string, unknown>} */
const textarea = (name, label, opts = {}) => ({
  name,
  label,
  type: 'string',
  ui: { component: 'textarea' },
  ...opts,
})

/**
 * What an editor's pick must be stored as: `/assets/images/<file>`, the one shape a
 * deployed save round-trips unchanged (test/image-ref.test.ts traces why).
 *
 * The media picker hands the field the full CDN URL (TinaMediaStore.parse returns
 * `img.src`), and for an image field nested inside a rich-text object list —
 * PhotoBand photos, LogoCards cards — TinaCloud writes that form value into the MDX
 * verbatim: its cloud→relative rewrite covers only direct props (@tinacms/mdx,
 * stringifyProps). That code runs on TinaCloud's servers, so it can't be patched
 * here; normalising in the form is the seam we own. Runs only on change, so values
 * an editor never touches still take TinaCloud's own conversion.
 *
 * Uploads are flat under mediaRoot, so the basename is the identity. Idempotent
 * across every shape the CMS has produced — CDN URL, `/assets/images/…`, bare
 * filename, the historical mangles — which keeps it safe on either side of a Tina
 * upgrade. Deliberately separate from imageKey (src/lib/images.ts): that one is
 * render-side tolerance for anything already stored; this one defines the single
 * shape a save may write.
 *
 * Markdown-body inline images need no equivalent: they go through the server
 * resolver on both read and write.
 * @type {(value: unknown) => unknown}
 */
export const imageRef = (value) => {
  if (!value || typeof value !== 'string') return value
  const base = value.split('/').pop()?.split('?')[0]
  return base ? `/assets/images/${base}` : value
}

/**
 * The ONLY way to declare an image field, anywhere in the CMS schema — exported
 * so tina/config.ts uses it too, and test/image-fields.test.ts fails the build
 * on an image field written by hand. The helper exists to make the imageRef
 * parse impossible to forget: an image field without it stores whatever shape
 * the picker or TinaCloud hands it, which looks fine locally and breaks only in
 * the deployed admin (mangled thumbnails, refs that don't round-trip) — the
 * photo catalog shipped exactly that once.
 * @type {(name: string, label: string, opts?: FieldOpts) => Record<string, unknown>}
 */
export const image = (name, label, opts = {}) => ({
  name,
  label,
  type: 'image',
  ...opts,
  ui: { parse: imageRef, ...(typeof opts.ui === 'object' ? opts.ui : {}) },
})

// Note on defaults: `ui.defaultValue` is a no-op — tinacms never forwards it to
// the rendered field — so a block's starting values live in the template's
// `ui.defaultItem`, which the editor genuinely applies when the block is added.
// It must sit under `ui`: schema-tools' rich-text field resolution keeps only
// label/key/name/fields plus whatever `ui` carries, so a top-level defaultItem
// on a rich-text template is silently dropped (verified in the running editor).

/** @type {(name: string, label: string, opts?: FieldOpts) => Record<string, unknown>} */
const bool = (name, label, opts = {}) => ({
  name,
  label,
  type: 'boolean',
  ...opts,
})

/**
 * A background-tone select. Labels are what the editor sees — the color, in plain words;
 * values are the design-system tone names (sand, paper, forest) the CSS uses.
 */
const TONE = {
  sand: { label: 'Warm sand', value: 'sand' },
  paper: { label: 'White', value: 'paper' },
  forest: { label: 'Dark green', value: 'forest' },
  none: { label: 'None (no band)', value: 'none' },
}
/** @type {(options: (keyof typeof TONE)[], opts?: FieldOpts) => Record<string, unknown>} */
const tone = (options, opts = {}) => ({
  name: 'tone',
  label: 'Background',
  type: 'string',
  options: options.map((o) => TONE[o]),
  ...opts,
})

/**
 * A button: its words, then where it goes. Every button on the site falls back to
 * "Learn more" (PageHero, SplitTina, ClosingTina) and shows only when it has a link.
 * @type {() => Record<string, unknown>[]}
 */
const button = () => [
  text('buttonLabel', 'Button text (optional)', { description: 'Leave blank for “Learn more”.' }),
  text('buttonHref', 'Button link', {
    description: 'The button appears once this is filled in: a page here like /visit/, or a full https:// address.',
    ui: { validate: checkOptionalLink },
  }),
]

/**
 * A link's words and its address, in that order, under the same two labels everywhere.
 * `required` makes the address required (Link cards, where the card is the link);
 * otherwise both may be blank. Field names vary by block because they're stored, so
 * they're passed in rather than renamed.
 * @type {(o: { textName: string, hrefName: string, textHelp?: string, hrefHelp?: string, required?: boolean }) => Record<string, unknown>[]}
 */
const linkFields = ({ textName, hrefName, textHelp, hrefHelp, required = false }) => [
  text(textName, 'Link text (optional)', textHelp ? { description: textHelp } : {}),
  text(hrefName, required ? 'Links to' : 'Links to (optional)', {
    ...(required ? { required: true } : {}),
    description: hrefHelp ?? 'A page here like /visit/, or a full https:// address.',
    ui: { validate: required ? checkLinkUrl : checkOptionalLink },
  }),
]

/** Label a list's collapsed rows by one of its own fields, so a gallery isn't N identical bars. */
/** @type {(key: string, fallback: string) => Record<string, unknown>} */
const itemProps = (key, fallback) => ({
  itemProps: (/** @type {Record<string, string> | undefined} */ item) => ({
    label: item?.[key] || fallback,
  }),
})

/* ----------------------------------------------------------------------
 * Hero fields
 *
 * Which kind of hero a page gets is an explicit choice — the `variant` select
 * below — rather than something inferred from which optional fields happen to
 * be filled in. That inference is what this replaced: a photo hero was "the one
 * where `image` was set", so a photo hero saved without a photo silently became
 * a text-only header and nothing could flag it. `variant` is the discriminator
 * src/content.config.ts validates against, so now that mistake fails the build.
 *
 * It would be better still if picking a variant hid the fields it doesn't use,
 * and Tina can't do that. Two dead ends, both tried:
 *
 *   - Conditional visibility needs a React component in `ui.component` reading
 *     form state. This file is plain .mjs, importable without a build step, and
 *     config.ts deliberately holds no JSX.
 *   - `type: 'object'` with `templates` — the documented "pick a shape, see only
 *     its fields" mechanism — is only implemented for *lists*. Non-list is
 *     literally `component: field.list ? 'blocks' : 'not-implemented'`
 *     (@tinacms/schema-tools 2.8.3, the current release), and the form renders
 *     "Unrecognized field type" where the hero should be. Shipped once; don't
 *     try it again without checking that line first.
 *
 * So the variants are documented in each field's description instead, and the
 * editor reads rather than is shown. If Tina implements non-list templates, the
 * shape here maps onto them directly.
 *
 * `required` is deliberately absent except inside the photo list's image field.
 * These are collection fields: a required one becomes non-null in GraphQL, and
 * the indexer then rejects any already-saved page missing it (see the note in
 * tina/config.ts). Alt fields on photo slots are optional on purpose: blank
 * falls back to the photo catalog (see photoAlt above), and check-site.mjs
 * fails the build on an image that renders with no alt from either source.
 * -------------------------------------------------------------------- */

/**
 * Which hero kinds a field applies to, prepended to its description. A field without
 * one applies to every kind — the variant select's own description says so.
 * @type {(which: string, rest: string) => string}
 */
const forVariants = (which, rest) => `For ${which}. ${rest}`

/** The small label above a heading. Stored as `eyebrow`, the design-system name for it. */
const eyebrow = () =>
  text('eyebrow', 'Small label above the heading (optional)', {
    description: 'A few words, like “In the community”.',
  })

/**
 * The alt field on every *catalogued-photo* slot. Blank falls back to the photo's
 * entry in "Photo descriptions" (altFor, src/lib/photos.ts), so the description is
 * written once and inherited everywhere the photo appears — hence a label that reads
 * as an override rather than as a field to fill in — until the photo beside it is one
 * the catalog doesn't know, when it asks (checkPhotoAlt). Every photo slot names its
 * picture `image`, which is the sibling it reads. Logo alt fields don't use this: logos
 * aren't catalogued, so theirs are genuinely required.
 * @type {(prefix?: (rest: string) => string) => Record<string, unknown>}
 */
const photoAlt = (prefix = (rest) => rest) =>
  text('alt', 'Different description for this page (optional)', {
    description: prefix(
      `Leave blank to use the photo’s saved description. ${guide('add-a-photo', 'About photo descriptions')}`
    ),
    ui: {
      /** @type {Validate} */
      validate: (value, allValues, _meta, field) =>
        checkPhotoAlt(value, siblingValue(allValues, field?.name, 'image'), CATALOGUED),
    },
  })

/**
 * The variant the form currently has, wherever the callback finds itself: a field
 * nested under `hero` gets the whole document as `allValues`, but keep the direct
 * shape working too so the check can't silently die on a Tina change.
 * @type {(allValues: unknown) => string | undefined}
 */
const heroVariant = (allValues) => {
  const values = /** @type {{ hero?: { variant?: string }, variant?: string } | undefined} */ (allValues)
  return values?.hero?.variant ?? values?.variant
}

export const heroFields = [
  {
    name: 'variant',
    label: 'Kind',
    type: 'string',
    options: [
      { label: 'Photo & text: a portrait photo beside the title', value: 'photo' },
      { label: 'Text only: a calm header, no photo', value: 'plain' },
      { label: 'Logo & photo: a program’s wordmark instead of the title', value: 'wordmark' },
      { label: 'Cinematic: a full-width photo stack (home page only)', value: 'cinematic' },
    ],
    // No ui.defaultValue — it's a no-op (see the note above bool()). New pages
    // are seeded 'photo' by the collection's defaultItem in tina/config.ts.
    description: `Pick this first. Fields marked “For …” apply only to those kinds. ${guide('add-a-page', 'Which kind?')}`,
  },
  // The two validates below mirror what the discriminated union in
  // src/content.config.ts will reject at build time — a "Photo & text" hero
  // saved without its photo used to preview fine and then fail a deploy the
  // editor never sees. Same rule, moved to where the editor is standing.
  image('image', 'Photo', {
    description: forVariants('Photo & text, Logo & photo', 'A portrait-shaped photo.'),
    ui: {
      validate: (/** @type {unknown} */ value, /** @type {unknown} */ allValues) =>
        heroVariant(allValues) === 'photo' && !value ? 'A “Photo & text” hero needs a photo.' : undefined,
    },
  }),
  photoAlt((rest) => forVariants('Photo & text, Logo & photo', rest)),
  {
    name: 'photos',
    label: 'Photos (cinematic)',
    type: 'object',
    list: true,
    openFormOnCreate: true,
    description: forVariants('Cinematic', 'They cross-fade in order; about five works well.'),
    // No `ui.min: 1`, even though src/content.config.ts requires at least one photo for
    // a cinematic hero. `min` disables Delete at the floor, and this list is shared by
    // all four variants — a photo added by mistake on a Photo & text page could then
    // never be removed. The zod check is variant-aware; this field can't be.
    ui: itemProps('alt', 'Photo'),
    fields: [image('image', 'Photo', { required: true }), photoAlt()],
  },
  image('logo', 'Wordmark logo', {
    description: forVariants('Logo & photo', 'Replaces the heading, like the Pine Lake Kids wordmark.'),
    ui: {
      validate: (/** @type {unknown} */ value, /** @type {unknown} */ allValues) =>
        heroVariant(allValues) === 'wordmark' && !value ? 'A “Logo & photo” hero needs its wordmark logo.' : undefined,
    },
  }),
  text('logoAlt', 'Logo description', {
    description: forVariants('Logo & photo', 'What the wordmark says, like “Pine Lake Kids”.'),
    ui: {
      validate: (/** @type {unknown} */ value, /** @type {unknown} */ allValues) =>
        heroVariant(allValues) === 'wordmark' && !value
          ? 'A “Logo & photo” hero needs the logo description — it stands in for the page heading.'
          : undefined,
    },
  }),
  eyebrow(),
  text('subhead', 'Subhead (optional)', { description: 'A line between the heading and the intro.' }),
  textarea('lede', 'Intro line', {
    description: forVariants(
      'Photo & text, Text only, Logo & photo',
      'One or two sentences under the title. If it could describe any church, rewrite it.'
    ),
  }),
  ...button(),
]

/**
 * The page's SEO description is optional only while the hero's intro line can stand in
 * for it — the rule src/pages/[...slug].astro renders by, and the one
 * scripts/check-site.mjs fails the build on. A cinematic hero never shows its intro line,
 * so it can't stand in there even if one was left behind by a variant switch.
 *
 * Only a page about to be published is held to it. Tina refuses to open any nested form
 * (the hero, a block) while the page form is invalid, and the intro line that would
 * satisfy this lives inside the hero — so on a new page, which starts with neither, the
 * rule locked the editor out of the very field that fixes it. Drafts never reach a build
 * ([...slug].astro filters them in production), so nothing is lost by waiting: the rule
 * speaks when "draft" is unticked, which is the moment it starts to matter.
 * @type {(value: unknown, allValues: unknown) => string | undefined}
 */
export const checkSeoDescription = (value, allValues) => {
  if (typeof value === 'string' && value.trim()) return undefined
  if (/** @type {{ draft?: unknown } | undefined} */ (allValues)?.draft === true) return undefined
  const lede = /** @type {{ hero?: { lede?: unknown } } | undefined} */ (allValues)?.hero?.lede
  const hasLede = heroVariant(allValues) !== 'cinematic' && typeof lede === 'string' && lede.trim() !== ''
  return hasLede
    ? undefined
    : 'To publish, this page needs a Search summary or an intro line at the top of the page — search results and link previews show it.'
}

// A block's `label` names how it looks ("Photo beside text", "Note with logo"), which is
// what an editor matches against the palette thumbnail and the page in front of them.
// Its `description` answers the other question — "I have something to say; is this
// where it goes?" — in the words of the "Which block do I use?" chooser.
export const templates = [
  {
    name: 'Section',
    label: 'Text',
    description: 'A few paragraphs that just need to be read. The default for written content.',
    ui: { ...itemProps('heading', 'Text'), previewSrc: preview('Section') },
    // The only wrapper whose heading is optional, so its prose may be the first
    // thing under the page's h1 — h2 stays available here alone.
    fields: [eyebrow(), text('heading', 'Heading (optional)'), prose(['h2', 'h3', 'h4'])],
  },
  {
    name: 'Split',
    label: 'Photo beside text',
    description: 'Something better shown than described: a photo beside a heading and a few paragraphs.',
    ui: {
      defaultItem: { tone: 'sand', reverse: false },
      ...itemProps('heading', 'Photo beside text'),
      previewSrc: preview('Split'),
    },
    // `ui.itemProps` puts the heading on the block's collapsed bar in the editor, so
    // a page of Splits doesn't read as identical grey bars. `isTitle` would do the
    // same, but Tina demands `required: true` alongside it and `heading` can't be
    // non-null here — see `needed()`. The same applies to the other blocks that
    // label their bar below.
    fields: [
      eyebrow(),
      text('heading', 'Heading', needed('This block needs a heading.')),
      image('image', 'Photo', needed('This block needs a photo.')),
      photoAlt(),
      prose(),
      ...button(),
      tone(['sand', 'paper', 'forest'], {
        description: 'Alternate the color when two of these blocks sit next to each other.',
      }),
      bool('reverse', 'Photo on the right'),
    ],
  },
  {
    name: 'Callout',
    label: 'Callout',
    description: 'One point you don’t want people to skim past, boxed with its own heading.',
    ui: { ...itemProps('heading', 'Callout'), previewSrc: preview('Callout') },
    fields: [text('heading', 'Heading', needed('This block needs a heading.')), prose()],
  },
  {
    name: 'CaptionedPhoto',
    label: 'Photo',
    description: 'A single photo that needs explaining, with a caption underneath.',
    ui: { ...itemProps('caption', 'Photo'), previewSrc: preview('CaptionedPhoto') },
    fields: [
      image('image', 'Photo', needed('This block needs a photo.')),
      photoAlt(),
      text('caption', 'Caption (optional)'),
    ],
  },
  {
    name: 'Video',
    label: 'Video',
    description: 'A YouTube or Vimeo video that says it better than a page.',
    ui: { ...itemProps('title', 'Video'), previewSrc: preview('Video') },
    fields: [
      text('url', 'Video link', {
        required: true,
        // The same parse the renderer uses, so "will this link work?" is answered
        // in the form rather than by a broken preview.
        ui: { validate: (/** @type {unknown} */ value) => checkVideoUrl(value) },
        description: 'Copy it from the browser’s address bar on YouTube or Vimeo, not the embed code.',
      }),
      text('title', 'Video title', {
        isTitle: true,
        required: true,
        description: 'A few words saying what the video is, for people using screen readers.',
      }),
      text('caption', 'Caption (optional)'),
    ],
  },
  {
    // Was "Banner", a general-purpose tonal band with tone and flush as options.
    // Every one of its uses was a page's closing block, every one was forest, and
    // two of five had missed the flush tick its own description asked for — three
    // fields carrying no information and one already got wrong. Narrowing it to
    // the thing it was actually used for lets the layout be fixed in code.
    name: 'Closing',
    label: 'Closing banner',
    description: 'The one thing you want the reader to do at the end. A dark band; one per page, and last.',
    ui: { ...itemProps('heading', 'Closing banner'), previewSrc: preview('Closing') },
    fields: [eyebrow(), text('heading', 'Heading', needed('This block needs a heading.')), prose(), ...button()],
  },
  {
    name: 'PhotoBand',
    label: 'Photo gallery',
    description: 'A moment of visual breathing room: several photos together, with few or no words.',
    ui: { ...itemProps('heading', 'Photo gallery'), previewSrc: preview('PhotoBand') },
    fields: [
      eyebrow(),
      text('heading', 'Heading (optional)'),
      {
        name: 'photos',
        label: 'Photos',
        type: 'object',
        list: true,
        openFormOnCreate: true,
        ui: itemProps('alt', 'Photo'),
        fields: [image('image', 'Photo', { required: true }), photoAlt()],
      },
    ],
  },
  {
    name: 'CardRow',
    label: 'Text cards',
    description: 'Three or four parallel things, each a short title and a line or two.',
    ui: {
      defaultItem: { columns: 'auto', large: false },
      ...itemProps('heading', 'Text cards'),
      previewSrc: preview('CardRow'),
    },
    fields: [
      eyebrow(),
      text('heading', 'Heading (optional)'),
      textarea('intro', 'Intro (optional)', { description: 'A line above the cards.' }),
      {
        name: 'cards',
        label: 'Cards',
        type: 'object',
        list: true,
        openFormOnCreate: true,
        ui: itemProps('title', 'Card'),
        fields: [
          text('title', 'Title', { required: true }),
          textarea('body', 'Text', { required: true }),
          ...linkFields({
            textName: 'linkLabel',
            hrefName: 'href',
            textHelp: 'Shown at the foot of the card with an arrow. Needs a link below.',
            hrefHelp: 'Makes the whole card a link: a page here like /visit/, or a full https:// address.',
          }),
        ],
      },
      {
        name: 'columns',
        label: 'Cards per row',
        type: 'string',
        options: [
          { label: 'Auto', value: 'auto' },
          { label: 'Two', value: '2' },
          { label: 'Three', value: '3' },
          { label: 'Four', value: '4' },
        ],
        description: 'Auto fits as many as there’s room for. Two makes four cards a 2×2 grid.',
      },
      bool('large', 'Large cards', { description: 'Roomier cards with a bigger title.' }),
    ],
  },
  {
    name: 'LinkCards',
    label: 'Link cards',
    description: 'Three or four places to go next, each card a link to another page.',
    ui: { ...itemProps('heading', 'Link cards'), previewSrc: preview('LinkCards') },
    fields: [
      text('heading', 'Heading', needed('This block needs a heading.')),
      {
        name: 'links',
        label: 'Links',
        type: 'object',
        list: true,
        openFormOnCreate: true,
        ui: itemProps('title', 'Link'),
        fields: [
          text('title', 'Title', { required: true }),
          text('meta', 'Text', { required: true, description: 'A line saying what’s there.' }),
          text('href', 'Links to', {
            required: true,
            description: 'A page here like /visit/, or a full https:// address.',
            ui: { validate: checkLinkUrl },
          }),
        ],
      },
    ],
  },
  {
    name: 'Quote',
    label: 'Quote',
    description: 'One thing someone said, worth its own space: a testimonial, a quotation, a verse.',
    ui: { defaultItem: { tone: 'none' }, ...itemProps('quote', 'Quote'), previewSrc: preview('Quote') },
    fields: [
      textarea('quote', 'Quote', { isTitle: true, required: true }),
      text('attribution', 'Who said it (optional)', {
        description: 'Like “A recent visitor”, or a Bible reference.',
      }),
      tone(['none', 'forest', 'sand', 'paper'], { description: 'None sets the quote in open space.' }),
    ],
  },
  {
    name: 'FeaturedEvents',
    label: 'Featured events',
    description:
      '“What’s coming up”, pulled from the calendar so it stays current. Shows nothing when nothing matches.',
    ui: {
      defaultItem: { category: 'all', count: 3 },
      ...itemProps('heading', 'Featured events'),
      previewSrc: preview('FeaturedEvents'),
    },
    fields: [
      text('heading', 'Heading (optional)'),
      {
        name: 'category',
        label: 'Category',
        type: 'string',
        description: 'Show only events tagged with this category.',
        options: [
          { label: 'All categories', value: 'all' },
          { label: 'Everyone', value: 'Everyone' },
          { label: 'Families', value: 'Families' },
          { label: 'Youth', value: 'Youth' },
          { label: 'Groups', value: 'Groups' },
          { label: 'Serve', value: 'Serve' },
        ],
      },
      {
        name: 'count',
        label: 'How many to show',
        type: 'number',
        description: 'From 1 to 12; three suits most pages.',
        ui: {
          validate: (/** @type {unknown} */ value) =>
            typeof value === 'number' && (value < 1 || value > 12) ? 'Pick a number from 1 to 12.' : undefined,
        },
      },
    ],
  },
  {
    name: 'KeyPoints',
    label: 'Key points',
    description: 'A set of principles where the order doesn’t matter, each a title and a line or two.',
    ui: { defaultItem: { columns: '2' }, ...itemProps('heading', 'Key points'), previewSrc: preview('KeyPoints') },
    fields: [
      eyebrow(),
      text('heading', 'Heading (optional)'),
      {
        name: 'items',
        label: 'Points',
        type: 'object',
        list: true,
        openFormOnCreate: true,
        ui: itemProps('title', 'Point'),
        fields: [text('title', 'Title', { required: true }), textarea('body', 'Text', { required: true })],
      },
      {
        name: 'columns',
        label: 'Columns',
        type: 'string',
        options: [
          { label: 'Two across', value: '2' },
          { label: 'Three across', value: '3' },
        ],
      },
    ],
  },
  {
    name: 'LogoCards',
    label: 'Logo cards',
    description: 'Cards each topped by a logo, with a line of text and an optional link.',
    ui: { ...itemProps('heading', 'Logo cards'), previewSrc: preview('LogoCards') },
    fields: [
      eyebrow(),
      text('heading', 'Heading', needed('This block needs a heading.')),
      {
        name: 'cards',
        label: 'Cards',
        type: 'object',
        list: true,
        openFormOnCreate: true,
        ui: itemProps('alt', 'Card'),
        fields: [
          image('image', 'Logo', { required: true }),
          text('alt', 'Logo description', { required: true, description: 'What the logo says or shows.' }),
          textarea('body', 'Text', { required: true }),
          ...linkFields({ textName: 'linkLabel', hrefName: 'href', textHelp: 'Leave blank for “Learn more”.' }),
        ],
      },
    ],
  },
  {
    // Merging this into Callout was considered and rejected: they share no layout
    // (Callout is a heading over text with an accent rule; this is a compact panel
    // beside a logo), so one block would need a switch that changes its whole shape,
    // and three extra fields on every Callout.
    name: 'Aside',
    label: 'Note with logo',
    description: 'A short note in a tinted panel, with room for a logo beside it.',
    ui: { ...itemProps('eyebrow', 'Note with logo'), previewSrc: preview('Aside') },
    fields: [
      eyebrow(),
      image('logo', 'Logo (optional)'),
      text('logoAlt', 'Logo description', {
        description: 'What the logo says or shows. Needed whenever there’s a logo.',
        ui: {
          /** @type {Validate} */
          validate: (value, allValues, _meta, field) =>
            siblingValue(allValues, field?.name, 'logo') && !value
              ? 'A logo needs a description for people who can’t see it.'
              : undefined,
        },
      }),
      prose(),
    ],
  },
  {
    name: 'YouthMomentsBlock',
    label: 'Youth moments',
    description: 'The youth year’s trips and retreats, from the shared Youth moments list.',
    ui: { ...itemProps('heading', 'Youth moments'), previewSrc: preview('YouthMomentsBlock') },
    fields: [eyebrow(), text('heading', 'Heading (optional)')],
  },
  {
    name: 'QuoteCarousel',
    label: 'Quotes carousel',
    description: 'Voices of the church, side by side, from the shared Homepage quotes list.',
    ui: {
      defaultItem: { tone: 'sand' },
      ...itemProps('heading', 'Quotes carousel'),
      previewSrc: preview('QuoteCarousel'),
    },
    fields: [
      eyebrow(),
      text('heading', 'Heading (optional)'),
      textarea('intro', 'Intro (optional)'),
      tone(['sand', 'paper', 'forest']),
    ],
  },
  {
    name: 'Roadmap',
    label: 'Roadmap',
    description: 'Steps where the order matters, numbered along a line.',
    ui: { ...itemProps('heading', 'Roadmap'), previewSrc: preview('Roadmap') },
    fields: [
      eyebrow(),
      text('heading', 'Heading (optional)'),
      {
        name: 'steps',
        label: 'Steps',
        type: 'object',
        list: true,
        openFormOnCreate: true,
        ui: itemProps('title', 'Step'),
        fields: [text('title', 'Title', { required: true }), textarea('body', 'Text', { required: true })],
      },
    ],
  },
  {
    name: 'Letter',
    label: 'Letter',
    description: 'A personal note in someone’s own voice, beside their portrait and closing with a signature.',
    ui: { ...itemProps('signoffName', 'Letter'), previewSrc: preview('Letter') },
    fields: [
      image('image', 'Portrait (optional)'),
      photoAlt(),
      prose(),
      text('signoffName', 'Signed by (optional)', { description: 'The name under the letter.' }),
      text('signoffRole', 'Their role (optional)', { description: 'Like “Lead Pastor”.' }),
    ],
  },
]
